name: maid_chan
description: Maid-chan clone.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter_dotenv: ^5.1.0
  nyxx: ^6.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0

assets:
  - .env
