name: bots
description: Bots in Dart.
version: 0.1.0
repository: https://github.com/veehz/dart-maid-chan

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  nyxx: ^6.1.0
  nyxx_commands: ^6.0.2

dev_dependencies:
  lints: ^3.0.0
